# Generated by Django 5.0.4 on 2024-04-19 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='note_type',
            field=models.CharField(choices=[('plain', 'Plain Note'), ('highlighted', 'Highlighted Note')], default='plain', max_length=11),
        ),
        migrations.AlterField(
            model_name='note',
            name='selected_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
