# Generated by Django 5.0.4 on 2024-04-19 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_note_type_alter_note_selected_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='HighlightedNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_text', models.TextField()),
                ('note_text', models.TextField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlighted_notes', to='notes.article')),
            ],
        ),
        migrations.CreateModel(
            name='PlainNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plain_notes', to='notes.article')),
            ],
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
