# Generated by Django 5.0.4 on 2024-04-19 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_highlightednote_plainnote_delete_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlightednote',
            name='end_position',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='highlightednote',
            name='start_position',
            field=models.IntegerField(default=0),
        ),
    ]
